# Generated by Django 5.1.5 on 2025-05-21 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PaymentMethod', '0003_historicalpaymentmethod'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalPaymentMethod',
        ),
    ]
