# Generated by Django 5.1.5 on 2025-04-20 12:51

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='project_images/'),
        ),
    ]
