# Generated by Django 5.1.5 on 2025-05-05 20:30

import imagekit.models.fields
import shared.utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_projectimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(default='default.jpg', upload_to=shared.utils.unique_project_image_upload_path),
        ),
    ]
