# Generated by Django 5.1.5 on 2025-05-18 18:15

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_projectcategory_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcategory',
            name='color',
            field=colorfield.fields.ColorField(default='#7c3aed', image_field=None, max_length=25, samples=None),
        ),
    ]
