# Generated by Django 5.1.5 on 2025-04-15 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_founder',
            field=models.BooleanField(default=False),
        ),
    ]
