# Generated by Django 5.1.5 on 2025-04-20 12:51

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pfp',
            field=imagekit.models.fields.ProcessedImageField(default='default.jpg', upload_to='profile_pics/'),
        ),
    ]
