# Generated by Django 5.1.5 on 2025-05-05 18:24

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_pfp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pfp',
            field=imagekit.models.fields.ProcessedImageField(default='default.jpeg', upload_to='profile_pics/'),
        ),
    ]
