# Generated by Django 5.1.5 on 2025-05-08 12:07

import imagekit.models.fields
import shared.utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_pfp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pfp',
            field=imagekit.models.fields.ProcessedImageField(default='default.jpg', upload_to=shared.utils.unique_image_upload_path),
        ),
    ]
